name: CI
on: [pull_request]
jobs:
    run:
        name: Run
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Set Node.js 12.x
              uses: actions/setup-node@v1
              with:
                  node-version: '12.x'

            - name: yarn install
              run: yarn install

            - name: Verify
              run: yarn verify
